# site settings
title: Wisebooks | Book Recommendations by World-class People
email: hello@wisebooks.io
description: Free database of books recommended by world-class people. Subscribe for bi-weekly bite-sized book recommendations.
baseurl:
url: https://www.wisebooks.io
author: Christine & Jenny

# homepage tiles
tiles-source: posts
tiles-count: 6

#collections
collections_dir: content
collections:
  - yc_founders
  - interviews
  - authors
  - PMs

#social settings
facebook_url:  https://www.facebook.com/wisebooksio/
twitter_url: https://twitter.com/wisebooksio

#mailchimp
mailchimp: https://wisebooks.us19.list-manage.com/subscribe/post?u=353a3edf5a036907ebe71dc44&amp;id=485976f620

# Tracker
analytics: UA-123321285-1 # Google Analytics

#permalink

permalink: :title/

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - liquid
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-compress-images


