# site settings
title: Wisebooks
email: wisebooksio@gmail.com
description: Good books read by smart people.
baseurl:
url: # the base hostname & protocol for your site
author: Christine & Jenny

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url:  https://facebook.com
instagram_url: https://instagram.com
pinterest_url:
slack_url:
twitter_url: https://twitter.com


#mailchimp
mailchimp: https://wisebooks.us19.list-manage.com/subscribe/post?u=353a3edf5a036907ebe71dc44&amp;id=485976f620

# Tracker
analytics: UA-113700903-1 # Google Analytics

# build settings
markdown: kramdown

sass:
  style: compressed
